services:
  postgres:
    image: public.ecr.aws/bitnami/postgresql:16
    container_name: mdams-local-postgres
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - mdams-local-postgres-data:/bitnami/postgresql

volumes:
  mdams-local-postgres-data:
    name: mdams-local-postgres-data
