"""initial schema

Revision ID: 001dea3060cf
Revises:
Create Date: 2026-06-23 12:25:35.105014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001dea3060cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_no', sa.String(), nullable=False),
    sa.Column('requester_name', sa.String(), nullable=False),
    sa.Column('requester_org', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('usage_scope', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('review_note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_application_no'), 'applications', ['application_no'], unique=True)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_key'), 'roles', ['key'], unique=True)
    op.create_table('three_d_collection_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_number', sa.String(), nullable=True),
    sa.Column('object_name', sa.String(), nullable=True),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('collection_unit', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_three_d_collection_objects_collection_unit'), 'three_d_collection_objects', ['collection_unit'], unique=False)
    op.create_index(op.f('ix_three_d_collection_objects_id'), 'three_d_collection_objects', ['id'], unique=False)
    op.create_index(op.f('ix_three_d_collection_objects_object_name'), 'three_d_collection_objects', ['object_name'], unique=False)
    op.create_index(op.f('ix_three_d_collection_objects_object_number'), 'three_d_collection_objects', ['object_number'], unique=False)
    op.create_index(op.f('ix_three_d_collection_objects_object_type'), 'three_d_collection_objects', ['object_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('collection_scope', sa.JSON(), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('video_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('process_message', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_assets_filename'), 'video_assets', ['filename'], unique=False)
    op.create_index(op.f('ix_video_assets_id'), 'video_assets', ['id'], unique=False)
    op.create_table('image_ingest_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_no', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('image_type', sa.String(), nullable=True),
    sa.Column('project_type', sa.String(), nullable=True),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('photographer', sa.String(), nullable=True),
    sa.Column('photographer_org', sa.String(), nullable=True),
    sa.Column('copyright_owner', sa.String(), nullable=True),
    sa.Column('capture_time', sa.String(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_photographer_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_photographer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_ingest_sheets_assigned_photographer_user_id'), 'image_ingest_sheets', ['assigned_photographer_user_id'], unique=False)
    op.create_index(op.f('ix_image_ingest_sheets_created_by_user_id'), 'image_ingest_sheets', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_image_ingest_sheets_id'), 'image_ingest_sheets', ['id'], unique=False)
    op.create_index(op.f('ix_image_ingest_sheets_image_type'), 'image_ingest_sheets', ['image_type'], unique=False)
    op.create_index(op.f('ix_image_ingest_sheets_sheet_no'), 'image_ingest_sheets', ['sheet_no'], unique=True)
    op.create_index(op.f('ix_image_ingest_sheets_status'), 'image_ingest_sheets', ['status'], unique=False)
    op.create_table('three_d_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_object_id', sa.Integer(), nullable=True),
    sa.Column('resource_group', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('process_message', sa.String(), nullable=True),
    sa.Column('version_label', sa.String(), nullable=True),
    sa.Column('version_order', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('is_web_preview', sa.Boolean(), nullable=True),
    sa.Column('web_preview_status', sa.String(), nullable=True),
    sa.Column('web_preview_reason', sa.String(), nullable=True),
    sa.Column('storage_tier', sa.String(), nullable=True),
    sa.Column('preservation_status', sa.String(), nullable=True),
    sa.Column('preservation_note', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['collection_object_id'], ['three_d_collection_objects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_three_d_assets_collection_object_id'), 'three_d_assets', ['collection_object_id'], unique=False)
    op.create_index(op.f('ix_three_d_assets_filename'), 'three_d_assets', ['filename'], unique=False)
    op.create_index(op.f('ix_three_d_assets_id'), 'three_d_assets', ['id'], unique=False)
    op.create_index(op.f('ix_three_d_assets_resource_group'), 'three_d_assets', ['resource_group'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('image_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sheet_id', sa.Integer(), nullable=True),
    sa.Column('line_no', sa.Integer(), nullable=True),
    sa.Column('record_no', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('visibility_scope', sa.String(), nullable=True),
    sa.Column('collection_object_id', sa.Integer(), nullable=True),
    sa.Column('profile_key', sa.String(), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('assigned_photographer_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_photographer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sheet_id'], ['image_ingest_sheets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_records_assigned_photographer_user_id'), 'image_records', ['assigned_photographer_user_id'], unique=False)
    op.create_index(op.f('ix_image_records_collection_object_id'), 'image_records', ['collection_object_id'], unique=False)
    op.create_index(op.f('ix_image_records_created_by_user_id'), 'image_records', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_image_records_id'), 'image_records', ['id'], unique=False)
    op.create_index(op.f('ix_image_records_profile_key'), 'image_records', ['profile_key'], unique=False)
    op.create_index(op.f('ix_image_records_record_no'), 'image_records', ['record_no'], unique=True)
    op.create_index(op.f('ix_image_records_sheet_id'), 'image_records', ['sheet_id'], unique=False)
    op.create_index(op.f('ix_image_records_status'), 'image_records', ['status'], unique=False)
    op.create_index(op.f('ix_image_records_submitted_by_user_id'), 'image_records', ['submitted_by_user_id'], unique=False)
    op.create_index(op.f('ix_image_records_visibility_scope'), 'image_records', ['visibility_scope'], unique=False)
    op.create_table('three_d_asset_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('role_label', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('actual_filename', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['three_d_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_three_d_asset_files_asset_id'), 'three_d_asset_files', ['asset_id'], unique=False)
    op.create_index(op.f('ix_three_d_asset_files_filename'), 'three_d_asset_files', ['filename'], unique=False)
    op.create_index(op.f('ix_three_d_asset_files_id'), 'three_d_asset_files', ['id'], unique=False)
    op.create_index(op.f('ix_three_d_asset_files_role'), 'three_d_asset_files', ['role'], unique=False)
    op.create_table('three_d_production_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('evidence', sa.String(), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['three_d_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_three_d_production_records_asset_id'), 'three_d_production_records', ['asset_id'], unique=False)
    op.create_index(op.f('ix_three_d_production_records_event_type'), 'three_d_production_records', ['event_type'], unique=False)
    op.create_index(op.f('ix_three_d_production_records_id'), 'three_d_production_records', ['id'], unique=False)
    op.create_index(op.f('ix_three_d_production_records_stage'), 'three_d_production_records', ['stage'], unique=False)
    op.create_index(op.f('ix_three_d_production_records_status'), 'three_d_production_records', ['status'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('visibility_scope', sa.String(), nullable=True),
    sa.Column('collection_object_id', sa.Integer(), nullable=True),
    sa.Column('image_record_id', sa.Integer(), nullable=True),
    sa.Column('metadata_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('process_message', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['image_record_id'], ['image_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_collection_object_id'), 'assets', ['collection_object_id'], unique=False)
    op.create_index(op.f('ix_assets_filename'), 'assets', ['filename'], unique=False)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_index(op.f('ix_assets_image_record_id'), 'assets', ['image_record_id'], unique=True)
    op.create_index(op.f('ix_assets_visibility_scope'), 'assets', ['visibility_scope'], unique=False)
    op.create_table('application_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('source_system', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('resource_title', sa.String(), nullable=True),
    sa.Column('manifest_url', sa.String(), nullable=True),
    sa.Column('source_label', sa.String(), nullable=True),
    sa.Column('object_number', sa.String(), nullable=True),
    sa.Column('requested_variant', sa.String(), nullable=True),
    sa.Column('delivery_format', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_items_application_id'), 'application_items', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_items_asset_id'), 'application_items', ['asset_id'], unique=False)
    op.create_index(op.f('ix_application_items_id'), 'application_items', ['id'], unique=False)
    op.create_index(op.f('ix_application_items_source_id'), 'application_items', ['source_id'], unique=False)
    op.create_index(op.f('ix_application_items_source_system'), 'application_items', ['source_system'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_items_source_system'), table_name='application_items')
    op.drop_index(op.f('ix_application_items_source_id'), table_name='application_items')
    op.drop_index(op.f('ix_application_items_id'), table_name='application_items')
    op.drop_index(op.f('ix_application_items_asset_id'), table_name='application_items')
    op.drop_index(op.f('ix_application_items_application_id'), table_name='application_items')
    op.drop_table('application_items')
    op.drop_index(op.f('ix_assets_visibility_scope'), table_name='assets')
    op.drop_index(op.f('ix_assets_image_record_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_filename'), table_name='assets')
    op.drop_index(op.f('ix_assets_collection_object_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_three_d_production_records_status'), table_name='three_d_production_records')
    op.drop_index(op.f('ix_three_d_production_records_stage'), table_name='three_d_production_records')
    op.drop_index(op.f('ix_three_d_production_records_id'), table_name='three_d_production_records')
    op.drop_index(op.f('ix_three_d_production_records_event_type'), table_name='three_d_production_records')
    op.drop_index(op.f('ix_three_d_production_records_asset_id'), table_name='three_d_production_records')
    op.drop_table('three_d_production_records')
    op.drop_index(op.f('ix_three_d_asset_files_role'), table_name='three_d_asset_files')
    op.drop_index(op.f('ix_three_d_asset_files_id'), table_name='three_d_asset_files')
    op.drop_index(op.f('ix_three_d_asset_files_filename'), table_name='three_d_asset_files')
    op.drop_index(op.f('ix_three_d_asset_files_asset_id'), table_name='three_d_asset_files')
    op.drop_table('three_d_asset_files')
    op.drop_index(op.f('ix_image_records_visibility_scope'), table_name='image_records')
    op.drop_index(op.f('ix_image_records_submitted_by_user_id'), table_name='image_records')
    op.drop_index(op.f('ix_image_records_status'), table_name='image_records')
    op.drop_index(op.f('ix_image_records_sheet_id'), table_name='image_records')
    op.drop_index(op.f('ix_image_records_record_no'), table_name='image_records')
    op.drop_index(op.f('ix_image_records_profile_key'), table_name='image_records')
    op.drop_index(op.f('ix_image_records_id'), table_name='image_records')
    op.drop_index(op.f('ix_image_records_created_by_user_id'), table_name='image_records')
    op.drop_index(op.f('ix_image_records_collection_object_id'), table_name='image_records')
    op.drop_index(op.f('ix_image_records_assigned_photographer_user_id'), table_name='image_records')
    op.drop_table('image_records')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_three_d_assets_resource_group'), table_name='three_d_assets')
    op.drop_index(op.f('ix_three_d_assets_id'), table_name='three_d_assets')
    op.drop_index(op.f('ix_three_d_assets_filename'), table_name='three_d_assets')
    op.drop_index(op.f('ix_three_d_assets_collection_object_id'), table_name='three_d_assets')
    op.drop_table('three_d_assets')
    op.drop_index(op.f('ix_image_ingest_sheets_status'), table_name='image_ingest_sheets')
    op.drop_index(op.f('ix_image_ingest_sheets_sheet_no'), table_name='image_ingest_sheets')
    op.drop_index(op.f('ix_image_ingest_sheets_image_type'), table_name='image_ingest_sheets')
    op.drop_index(op.f('ix_image_ingest_sheets_id'), table_name='image_ingest_sheets')
    op.drop_index(op.f('ix_image_ingest_sheets_created_by_user_id'), table_name='image_ingest_sheets')
    op.drop_index(op.f('ix_image_ingest_sheets_assigned_photographer_user_id'), table_name='image_ingest_sheets')
    op.drop_table('image_ingest_sheets')
    op.drop_index(op.f('ix_video_assets_id'), table_name='video_assets')
    op.drop_index(op.f('ix_video_assets_filename'), table_name='video_assets')
    op.drop_table('video_assets')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_three_d_collection_objects_object_type'), table_name='three_d_collection_objects')
    op.drop_index(op.f('ix_three_d_collection_objects_object_number'), table_name='three_d_collection_objects')
    op.drop_index(op.f('ix_three_d_collection_objects_object_name'), table_name='three_d_collection_objects')
    op.drop_index(op.f('ix_three_d_collection_objects_id'), table_name='three_d_collection_objects')
    op.drop_index(op.f('ix_three_d_collection_objects_collection_unit'), table_name='three_d_collection_objects')
    op.drop_table('three_d_collection_objects')
    op.drop_index(op.f('ix_roles_key'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_application_no'), table_name='applications')
    op.drop_table('applications')
    # ### end Alembic commands ###
